### Pandas for Practical Tabular Preparation and Analysis

#### 1. Setup

- we import Pandas and NumPy then configure display options so tables are easier to read inside the notebook.

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\singh\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\singh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/10.0 MB 7.7 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/10.0 MB 7.4 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/10.0 MB 7.2 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/10.0 MB 7.2 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/10.0 MB 7.2 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/10.0 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 7.1 MB/s  0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
from pathlib import Path # For working with file paths in a platform-independent way.

import numpy as np
import pandas as pd


# Display settings are optional , but useful while exploring tables
# pd.set_option("display.max_columns", 80)  # display up to 80 columns in the output
# pd.set_option("display.width", 140) # Set the display width to 140 characters to prevent line wrapping in the output
# pd.set_option("display.float_format", lambda x: f"{x:,.3f}"") # format floating-point numbers with commas as thousands separators and 3 decimal places.

# print("Pandas version:", pd.__version__)
# print("NumPy version: ", np.__version__)

#### Common `pd.set_option()` settings used constantly in table work:

- **Display Rows**
  - `display.max_rows`
  - `display.min_rows`

- **Display Columns**
  - `display.max_columns`

- **Display Width**
  - `display.width`

- **Column Width**
  - `display.max_colwidth`

- **Floating Point Display**
  - `display.precision`
  - `display.float_format`

- **DataFrame Layout**
  - `display.expand_frame_repr`

- **Sequence Display**
  - `display.max_seq_items`

- **Large DataFrame Display**
  - `display.large_repr`

- **Maximum Information Columns**
  - `display.max_info_columns`

- **Maximum Information Rows**
  - `display.max_info_rows`

- **HTML Display (Jupyter)**
  - `display.html.use_mathjax`
  - `display.html.border`

- **General Option Functions**
  - `pd.set_option()`
  - `pd.get_option()`
  - `pd.reset_option()`
  - `pd.describe_option()`

In [5]:
pd.read_csv("Social_Media_Sentiment_Analysis_AI_Trends_2026.csv")

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,...,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
0,YouTube,YO_100000,user_2679,rxckafna,True,375410,Germany,I don’t agree with this at all.,ur,"#news,#update",...,Wed,True,Technology,Positive,0.82,Sad,0.10,False,True,https://www.youtube.com
1,Reddit,RE_100001,user_3045,zjovqwps,True,346702,UK,Worst decision ever made.,fr,"#trending,#ai",...,Tue,False,Sports,Neutral,-0.02,Angry,0.67,True,True,https://www.reddit.com
2,YouTube,YO_100002,user_4598,rvufaigf,False,111487,Germany,This trend is getting out of hand.,de,"#news,#update",...,Fri,False,Finance,Positive,0.62,Neutral,0.43,False,False,https://www.youtube.com
3,Twitter,TW_100003,user_3504,qukbjznz,True,356674,Germany,Pretty neutral about the update.,en,"#trending,#ai",...,Thu,True,Finance,Neutral,0.14,Sad,0.97,True,True,https://www.twitter.com
4,YouTube,YO_100004,user_3646,ounaiayw,False,125551,USA,"Loved the explanation, very helpful.",es,"#trending,#ai",...,Sun,True,Technology,Neutral,-0.05,Fear,0.95,True,False,https://www.youtube.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,Twitter,TW_102195,user_5562,wbmdjeyg,False,416073,Canada,This is absolutely amazing!,es,"#trending,#ai",...,Sat,True,Climate,Neutral,0.07,Fear,0.75,True,False,https://www.twitter.com
2196,Twitter,TW_102196,user_7076,jgagwoun,False,101979,Canada,I’m confused about the announcement.,ur,"#news,#update",...,Wed,False,Technology,Neutral,0.15,Fear,0.95,False,True,https://www.twitter.com
2197,YouTube,YO_102197,user_9327,ubafeuzh,True,386908,UK,"Not bad, but could be better.",ur,"#trending,#ai",...,Mon,False,Sports,Negative,-0.90,Fear,0.25,True,False,https://www.youtube.com
2198,Reddit,RE_102198,user_4002,zahccrkp,False,266478,UK,I’m confused about the announcement.,es,"#trending,#ai",...,Sun,True,Finance,Positive,0.91,Fear,0.43,True,False,https://www.reddit.com
2199,YouTube,YO_102199,user_4688,tolbdysn,False,338860,India,This is absolutely amazing!,fr,"#news,#update",...,Sat,True,Finance,Neutral,-0.19,Angry,0.13,False,False,https://www.youtube.com

In [8]:
# display all columns

pd.set_option("display.max_columns", 80)
pd.read_csv("Social_Media_Sentiment_Analysis_AI_Trends_2026.csv")

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,mentions,post_length,like_count,comment_count,share_count,engagement_score,posted_datetime,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
0,YouTube,YO_100000,user_2679,rxckafna,True,375410,Germany,I don’t agree with this at all.,ur,"#news,#update",NaN,31,9115,53,653,0.70,2024-12-14T00:00:00,Wed,True,Technology,Positive,0.82,Sad,0.10,False,True,https://www.youtube.com
1,Reddit,RE_100001,user_3045,zjovqwps,True,346702,UK,Worst decision ever made.,fr,"#trending,#ai",@user123,25,3309,3113,1138,0.45,2025-01-08T00:00:00,Tue,False,Sports,Neutral,-0.02,Angry,0.67,True,True,https://www.reddit.com
2,YouTube,YO_100002,user_4598,rvufaigf,False,111487,Germany,This trend is getting out of hand.,de,"#news,#update",@user123,34,15035,1170,1084,0.14,2025-07-28T00:00:00,Fri,False,Finance,Positive,0.62,Neutral,0.43,False,False,https://www.youtube.com
3,Twitter,TW_100003,user_3504,qukbjznz,True,356674,Germany,Pretty neutral about the update.,en,"#trending,#ai",NaN,32,8743,2786,456,0.29,2024-06-10T00:00:00,Thu,True,Finance,Neutral,0.14,Sad,0.97,True,True,https://www.twitter.com
4,YouTube,YO_100004,user_3646,ounaiayw,False,125551,USA,"Loved the explanation, very helpful.",es,"#trending,#ai",@user123,36,2806,3981,283,0.98,2025-06-29T00:00:00,Sun,True,Technology,Neutral,-0.05,Fear,0.95,True,False,https://www.youtube.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,Twitter,TW_102195,user_5562,wbmdjeyg,False,416073,Canada,This is absolutely amazing!,es,"#trending,#ai",NaN,27,4332,837,2845,0.79,2025-08-17T00:00:00,Sat,True,Climate,Neutral,0.07,Fear,0.75,True,False,https://www.twitter.com
2196,Twitter,TW_102196,user_7076,jgagwoun,False,101979,Canada,I’m confused about the announcement.,ur,"#news,#update",NaN,36,313,3869,1457,0.38,2025-04-05T00:00:00,Wed,False,Technology,Neutral,0.15,Fear,0.95,False,True,https://www.twitter.com
2197,YouTube,YO_102197,user_9327,ubafeuzh,True,386908,UK,"Not bad, but could be better.",ur,"#trending,#ai",NaN,29,9039,464,1002,0.14,2024-10-05T00:00:00,Mon,False,Sports,Negative,-0.90,Fear,0.25,True,False,https://www.youtube.com
2198,Reddit,RE_102198,user_4002,zahccrkp,False,266478,UK,I’m confused about the announcement.,es,"#trending,#ai",@user123,36,10588,1576,2133,0.12,2024-06-18T00:00:00,Sun,True,Finance,Positive,0.91,Fear,0.43,True,False,https://www.reddit.com
2199,YouTube,YO_102199,user_4688,tolbdysn,False,338860,India,This is absolutely amazing!,fr,"#news,#update",NaN,27,1979,2602,1038,0.69,2024-09-12T00:00:00,Sat,True,Finance,Neutral,-0.19,Angry,0.13,False,False,https://www.youtube.com

In [ ]:
# value should not get truncate
# This tells Pandas to assume your terminal is 140 characters wide before wrapping output.

pd.set_option("display.width", 140)
pd.read_csv("Social_Media_Sentiment_Analysis_AI_Trends_2026.csv")

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,mentions,post_length,like_count,comment_count,share_count,engagement_score,posted_datetime,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
0,YouTube,YO_100000,user_2679,rxckafna,True,375410,Germany,I don’t agree with this at all.,ur,"#news,#update",NaN,31,9115,53,653,0.70,2024-12-14T00:00:00,Wed,True,Technology,Positive,0.82,Sad,0.10,False,True,https://www.youtube.com
1,Reddit,RE_100001,user_3045,zjovqwps,True,346702,UK,Worst decision ever made.,fr,"#trending,#ai",@user123,25,3309,3113,1138,0.45,2025-01-08T00:00:00,Tue,False,Sports,Neutral,-0.02,Angry,0.67,True,True,https://www.reddit.com
2,YouTube,YO_100002,user_4598,rvufaigf,False,111487,Germany,This trend is getting out of hand.,de,"#news,#update",@user123,34,15035,1170,1084,0.14,2025-07-28T00:00:00,Fri,False,Finance,Positive,0.62,Neutral,0.43,False,False,https://www.youtube.com
3,Twitter,TW_100003,user_3504,qukbjznz,True,356674,Germany,Pretty neutral about the update.,en,"#trending,#ai",NaN,32,8743,2786,456,0.29,2024-06-10T00:00:00,Thu,True,Finance,Neutral,0.14,Sad,0.97,True,True,https://www.twitter.com
4,YouTube,YO_100004,user_3646,ounaiayw,False,125551,USA,"Loved the explanation, very helpful.",es,"#trending,#ai",@user123,36,2806,3981,283,0.98,2025-06-29T00:00:00,Sun,True,Technology,Neutral,-0.05,Fear,0.95,True,False,https://www.youtube.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,Twitter,TW_102195,user_5562,wbmdjeyg,False,416073,Canada,This is absolutely amazing!,es,"#trending,#ai",NaN,27,4332,837,2845,0.79,2025-08-17T00:00:00,Sat,True,Climate,Neutral,0.07,Fear,0.75,True,False,https://www.twitter.com
2196,Twitter,TW_102196,user_7076,jgagwoun,False,101979,Canada,I’m confused about the announcement.,ur,"#news,#update",NaN,36,313,3869,1457,0.38,2025-04-05T00:00:00,Wed,False,Technology,Neutral,0.15,Fear,0.95,False,True,https://www.twitter.com
2197,YouTube,YO_102197,user_9327,ubafeuzh,True,386908,UK,"Not bad, but could be better.",ur,"#trending,#ai",NaN,29,9039,464,1002,0.14,2024-10-05T00:00:00,Mon,False,Sports,Negative,-0.90,Fear,0.25,True,False,https://www.youtube.com
2198,Reddit,RE_102198,user_4002,zahccrkp,False,266478,UK,I’m confused about the announcement.,es,"#trending,#ai",@user123,36,10588,1576,2133,0.12,2024-06-18T00:00:00,Sun,True,Finance,Positive,0.91,Fear,0.43,True,False,https://www.reddit.com
2199,YouTube,YO_102199,user_4688,tolbdysn,False,338860,India,This is absolutely amazing!,fr,"#news,#update",NaN,27,1979,2602,1038,0.69,2024-09-12T00:00:00,Sat,True,Finance,Neutral,-0.19,Angry,0.13,False,False,https://www.youtube.com

### 2. Series: The One-Dimensional Building Block
 - A Series is a labled one-dimensional array. A single DataFrame column is a Series. Understanding Series operations makes DataFrame work much easier.

In [14]:
# default index

pd.Series(
    data=[1200,850,430,980])

0    1200
1     850
2     430
3     980
dtype: int64

In [15]:
sales_series = pd.Series(
    data=[1200,850,430,980],
    index=["West", "East", "South", "North"],
    name="monthly_sales"
)

print(sales_series)
print("\n series name", sales_series.name)
print("\n index labels", sales_series.index.tolist())
print("\n values as NumPy array", sales_series.to_numpy())

West     1200
East      850
South     430
North     980
Name: monthly_sales, dtype: int64

 series name monthly_sales

 index labels ['West', 'East', 'South', 'North']

 values as NumPy array [1200  850  430  980]

In [18]:
# Series arithmetic aligns by index labels.
# this is powerful because values match by label not just by positions

target_series = pd.Series(
    data=[1000, 900, 500, 900],
    index=["West", "East", "South", "North"],
    name="target",
)

difference = sales_series - target_series
achievement_ratio = sales_series / target_series

print("Difference from target: \n", difference)
print("Achievement ratio: \n ", achievement_ratio)

Difference from target:
 West     200
East     -50
South    -70
North     80
dtype: int64
Achievement ratio:
  West     1.200000
East     0.944444
South    0.860000
North    1.088889
dtype: float64

#### Commom Series methods used constantly in table work:
#### Common Series methods used constantly in table work:

- **Basic Information**
  - `head()`
  - `tail()`
  - `describe()`
  - `dtype`
  - `shape`
  - `size`

- **Missing Values**
  - `isna()`
  - `notna()`
  - `dropna()`
  - `fillna()`

- **Unique & Frequency**
  - `unique()`
  - `nunique()`
  - `value_counts()`

- **Sorting**
  - `sort_values()`
  - `sort_index()`

- **Mathematical Operations**
  - `sum()`
  - `mean()`
  - `median()`
  - `min()`
  - `max()`
  - `std()`
  - `var()`
  - `count()`

- **Boolean Filtering**
  - `isin()`

- **String Methods (`.str`)**
  - `str.lower()`
  - `str.upper()`
  - `str.title()`
  - `str.strip()`
  - `str.contains()`
  - `str.replace()`
  - `str.startswith()`
  - `str.endswith()`
  - `str.len()`

- **Type Conversion**
  - `astype()`

- **Apply Functions**
  - `apply()`

- **Mapping**
  - `map()`

- **Replace Values**
  - `replace()`

- **Indexing**
  - `iloc`
  - `loc`

- **Duplicate Handling**
  - `duplicated()`
  - `drop_duplicates()`

- **Value Clipping**
  - `clip()`

- **Ranking**
  - `rank()`

- **Cumulative Operations**
  - `cumsum()`
  - `cummax()`
  - `cummin()`
  - `cumprod()`

- **Correlation**
  - `corr()`

In [22]:
# common series methods used constantly in table work.

s = pd.Series([10,20, np.nan, 20,30, 30, 30], name="example")
print("\n example series: \n", s)

print("count non-missing: ", s.count())

# to show true false if number is missing
print("missing numbers: ", s.isna())
print("number missing: ", s.isna().sum())  # number of missing values (basically count)

# find unique
print("Unique values \n: ", s.unique())

# freqency of number getting duplicate (number of time it come)
print("frequency table\n: ", s.value_counts(dropna=False))

# describe

print("\n summary statistics: \n", s.describe())

 example series:
 0    10.0
1    20.0
2     NaN
3    20.0
4    30.0
5    30.0
6    30.0
Name: example, dtype: float64
count non-missing:  6
missing numbers:  0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: example, dtype: bool
number missing:  1
Unique values
:  [10. 20. nan 30.]
frequency table
:  example
30.0    3
20.0    2
10.0    1
NaN     1
Name: count, dtype: int64

 summary statistics:
 count     6.000000
mean     23.333333
std       8.164966
min      10.000000
25%      20.000000
50%      25.000000
75%      30.000000
max      30.000000
Name: example, dtype: float64

In [ ]:
# String Series use the .str accessor.

names = pd.Series(["   office supplies       " , "furniture", "TECHNOLOGY", 'None'])

cleaned_names = (
    names
    .str.strip()  # remove leading/trailing spaces
    .str.title()  # convert to title case
    .fillna("Unknown") # replace missing text
)

print(cleaned_names)

0    Office Supplies
1          Furniture
2         Technology
3               None
4                Nan
dtype: str

In [ ]:
names.str.strip().str.title().fillna("Unknown")

#### fillna()

- It fills missing (NaN) values with a value we specify,

- s.fillna(0)

#### dropna()

- It deletes the row (or values in a Series) that contains NaN.
- s.dropna()

### DataFrame: Rows , Columns and Labeled Structure

- A DataFrame is a 2-Dimensional labeled table. It can be created from dictionaries, list of dictionaries, arrays, files , or database results.

In [27]:
# A small custom table is useful for learning core behaviour quicklu

small_orders = pd.DataFrame({
   "order_id": ["A001", "A002", "A003", "A004"],
   "region": ["West", "East", "West", "South"],
   "sales": [250.0, 180.0, 320.0, 90.0],
   "quantity": [3,2,4,1] 
})

small_orders

  order_id region  sales  quantity
0     A001   West  250.0         3
1     A002   East  180.0         2
2     A003   West  320.0         4
3     A004  South   90.0         1

In [29]:
# Add a derived column using vectorized arithmetic.
small_orders["sales_per_unit"] = small_orders["sales"] / small_orders["quantity"]

# assign returns a new DataFrame, which is convenient in method chains
small_orders = small_orders.assign(
    high_values=lambda d: d["sales"] >= 250
)

small_orders

  order_id region  sales  quantity  sales_per_unit  high_values
0     A001   West  250.0         3       83.333333         True
1     A002   East  180.0         2       90.000000        False
2     A003   West  320.0         4       80.000000         True
3     A004  South   90.0         1       90.000000        False

In [ ]:
# assign returns a new dataFrame, which is convenient in method chains

small_orders = small_orders.assign(high_value=lambda d: d["sales"] >= 250)

small_orders

# lambda x, y: 3 * x + 2 + 2 * y

  order_id region  sales  quantity  sales_per_unit  high_values  high_value
0     A001   West  250.0         3       83.333333         True        True
1     A002   East  180.0         2       90.000000        False       False
2     A003   West  320.0         4       80.000000         True        True
3     A004  South   90.0         1       90.000000        False       False

###  4. Load the superstone csv

In [33]:
# how to read the data

df_raw = pd.read_csv("Social_Media_Sentiment_Analysis_AI_Trends_2026.csv")

print("rows, columns: ", df_raw.shape)
# shape is not a function, so no parentheses needed.
# shape is an attribute that returns a tuple of (number of rows, number of columns).

rows, columns:  (2200, 27)

In [ ]:
# display the first 5 rows of the DataFrame to get the initial look at the data
df_raw.head()
# can add number of rows
df_raw.head(10)

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,mentions,post_length,like_count,comment_count,share_count,engagement_score,posted_datetime,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
0,YouTube,YO_100000,user_2679,rxckafna,True,375410,Germany,I don’t agree with this at all.,ur,"#news,#update",NaN,31,9115,53,653,0.70,2024-12-14T00:00:00,Wed,True,Technology,Positive,0.82,Sad,0.10,False,True,https://www.youtube.com
1,Reddit,RE_100001,user_3045,zjovqwps,True,346702,UK,Worst decision ever made.,fr,"#trending,#ai",@user123,25,3309,3113,1138,0.45,2025-01-08T00:00:00,Tue,False,Sports,Neutral,-0.02,Angry,0.67,True,True,https://www.reddit.com
2,YouTube,YO_100002,user_4598,rvufaigf,False,111487,Germany,This trend is getting out of hand.,de,"#news,#update",@user123,34,15035,1170,1084,0.14,2025-07-28T00:00:00,Fri,False,Finance,Positive,0.62,Neutral,0.43,False,False,https://www.youtube.com
3,Twitter,TW_100003,user_3504,qukbjznz,True,356674,Germany,Pretty neutral about the update.,en,"#trending,#ai",NaN,32,8743,2786,456,0.29,2024-06-10T00:00:00,Thu,True,Finance,Neutral,0.14,Sad,0.97,True,True,https://www.twitter.com
4,YouTube,YO_100004,user_3646,ounaiayw,False,125551,USA,"Loved the explanation, very helpful.",es,"#trending,#ai",@user123,36,2806,3981,283,0.98,2025-06-29T00:00:00,Sun,True,Technology,Neutral,-0.05,Fear,0.95,True,False,https://www.youtube.com

In [35]:
# display the last 5 rows of the DataFrame

df_raw.tail()

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,mentions,post_length,like_count,comment_count,share_count,engagement_score,posted_datetime,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
2195,Twitter,TW_102195,user_5562,wbmdjeyg,False,416073,Canada,This is absolutely amazing!,es,"#trending,#ai",NaN,27,4332,837,2845,0.79,2025-08-17T00:00:00,Sat,True,Climate,Neutral,0.07,Fear,0.75,True,False,https://www.twitter.com
2196,Twitter,TW_102196,user_7076,jgagwoun,False,101979,Canada,I’m confused about the announcement.,ur,"#news,#update",NaN,36,313,3869,1457,0.38,2025-04-05T00:00:00,Wed,False,Technology,Neutral,0.15,Fear,0.95,False,True,https://www.twitter.com
2197,YouTube,YO_102197,user_9327,ubafeuzh,True,386908,UK,"Not bad, but could be better.",ur,"#trending,#ai",NaN,29,9039,464,1002,0.14,2024-10-05T00:00:00,Mon,False,Sports,Negative,-0.90,Fear,0.25,True,False,https://www.youtube.com
2198,Reddit,RE_102198,user_4002,zahccrkp,False,266478,UK,I’m confused about the announcement.,es,"#trending,#ai",@user123,36,10588,1576,2133,0.12,2024-06-18T00:00:00,Sun,True,Finance,Positive,0.91,Fear,0.43,True,False,https://www.reddit.com
2199,YouTube,YO_102199,user_4688,tolbdysn,False,338860,India,This is absolutely amazing!,fr,"#news,#update",NaN,27,1979,2602,1038,0.69,2024-09-12T00:00:00,Sat,True,Finance,Neutral,-0.19,Angry,0.13,False,False,https://www.youtube.com

In [ ]:
#  randomly five rows

# 

# isse values change nahi hoga kind of seed value jaisa
df_raw.sample(5, random_state=42)

,platform,post_id,user_id,username,user_verified,user_followers_count,user_location,post_text,language,hashtags,mentions,post_length,like_count,comment_count,share_count,engagement_score,posted_datetime,day_of_week,is_trending_topic,topic_category,sentiment_label,sentiment_score,emotion_label,toxicity_score,sarcasm_detected,spam_flag,data_source_url
1451,YouTube,YO_101451,user_6032,cmgwvloe,False,153007,UK,"Not bad, but could be better.",fr,"#news,#update",NaN,29,12446,4410,2387,0.83,2025-10-17T00:00:00,Sat,False,Finance,Neutral,0.20,Fear,0.81,True,False,https://www.youtube.com
1334,Twitter,TW_101334,user_8555,hexlkamg,True,494791,USA,People need to talk about this more.,de,"#news,#update",NaN,36,19515,3940,2595,0.66,2024-03-26T00:00:00,Sun,True,Politics,Positive,0.79,Sad,0.57,False,True,https://www.twitter.com
1761,Reddit,RE_101761,user_9133,cvonpend,False,202472,Pakistan,This is absolutely amazing!,es,"#trending,#ai",NaN,27,6376,3075,533,0.60,2024-01-05T00:00:00,Tue,False,Climate,Neutral,-0.02,Sad,0.64,False,True,https://www.reddit.com
1735,YouTube,YO_101735,user_4614,tzgkeiab,True,451968,USA,I don’t agree with this at all.,ur,"#news,#update",@user123,31,135,328,2201,0.87,2024-07-02T00:00:00,Tue,True,Sports,Neutral,0.13,Angry,0.13,True,True,https://www.youtube.com
1576,YouTube,YO_101576,user_7165,qpgyuwcj,False,118750,UK,This trend is getting out of hand.,es,"#trending,#ai",NaN,34,12582,2621,886,0.95,2024-10-29T00:00:00,Fri,True,Climate,Neutral,-0.14,Angry,0.69,False,False,https://www.youtube.com

In [37]:
print("shape", df_raw.shape)

shape (2200, 27)

In [38]:
df_raw.columns

Index(['platform', 'post_id', 'user_id', 'username', 'user_verified', 'user_followers_count', 'user_location', 'post_text', 'language',
       'hashtags', 'mentions', 'post_length', 'like_count', 'comment_count', 'share_count', 'engagement_score', 'posted_datetime',
       'day_of_week', 'is_trending_topic', 'topic_category', 'sentiment_label', 'sentiment_score', 'emotion_label', 'toxicity_score',
       'sarcasm_detected', 'spam_flag', 'data_source_url'],
      dtype='str')

In [39]:
df_raw.dtypes

platform                    str
post_id                     str
user_id                     str
username                    str
user_verified              bool
user_followers_count      int64
user_location               str
post_text                   str
language                    str
hashtags                    str
mentions                    str
post_length               int64
like_count                int64
comment_count             int64
share_count               int64
engagement_score        float64
posted_datetime             str
day_of_week                 str
is_trending_topic          bool
topic_category              str
sentiment_label             str
sentiment_score         float64
emotion_label               str
toxicity_score          float64
sarcasm_detected           bool
spam_flag                  bool
data_source_url             str
dtype: object

In [40]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   platform              2200 non-null   str
 1   post_id               2200 non-null   str
 2   user_id               2200 non-null   str
 3   username              2200 non-null   str
 4   user_verified         2200 non-null   bool
 5   user_followers_count  2200 non-null   int64
 6   user_location         2200 non-null   str
 7   post_text             2200 non-null   str
 8   language              2200 non-null   str
 9   hashtags              2200 non-null   str
 10  mentions              872 non-null    str
 11  post_length           2200 non-null   int64
 12  like_count            2200 non-null   int64
 13  comment_count         2200 non-null   int64
 14  share_count           2200 non-null   int64
 15  engagement_score      2200 non-null   float64
 16  posted_datetime       2200 non-null   str
 17  day_of_week           2200 non-null   str
 18  is_trending_topic     2200 non-null   bool
 19  topic_category        2200 non-null   str
 20  sentiment_label       2200 non-null   str
 21  sentiment_score       2200 non-null   float64
 22  emotion_label         2200 non-null   str
 23  toxicity_score        2200 non-null   float64
 24  sarcasm_detected      2200 non-null   bool
 25  spam_flag             2200 non-null   bool
 26  data_source_url       2200 non-null   str
dtypes: bool(4), float64(3), int64(5), str(15)
memory usage: 404.0 KB