# Pandas

### what is Pandas?

#### Pandas is an open source Python library for data manipulation and analysis. It works on structured data.

In [53]:
import pandas as pd

In [54]:
df = pd.__version__
print(df)

3.0.3

#### DataFrame - jo frame data se bana hota hai usko dataframe bolte hai

In [55]:
#Dataframe

df = pd.DataFrame([1,2,3,4])
print(df)

   0
0  1
1  2
2  3
3  4

In [56]:
# add columns

df = pd.DataFrame({
    "Name": [1,2,3,4],
    "Age": [20,32,14,52],
    "Salary": [20000,30000,40000,50000]
})
print(df)

   Name  Age  Salary
0     1   20   20000
1     2   32   30000
2     3   14   40000
3     4   52   50000

In [57]:
df = pd.DataFrame([1,2,3,4], columns=["Col Name"])
print(df)

   Col Name
0         1
1         2
2         3
3         4

In [58]:
print(type(df))

<class 'pandas.DataFrame'>

In [59]:
data = {
    "Name": ['Arpita', 'Swati', 'Sweta'],
    "Age": [21,34,42],
    "Salary": [20000,30000,40000]
}

df = pd.DataFrame(data)
# df = pd.DataFrame(data=data)
print(df)

     Name  Age  Salary
0  Arpita   21   20000
1   Swati   34   30000
2   Sweta   42   40000

### Basic Dataframe Understanding

In [60]:
# to get top data, by default head will give 5 records from top

df.head()
# can also pass the parameter

     Name  Age  Salary
0  Arpita   21   20000
1   Swati   34   30000
2   Sweta   42   40000

In [61]:
df.tail()
# df.tail(2) can also pass parameter

     Name  Age  Salary
0  Arpita   21   20000
1   Swati   34   30000
2   Sweta   42   40000

In [62]:
#  how to find the total rows and columns

df.shape  # (Row X Columns)

(3, 3)

In [63]:
#  to find the columns name

df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [64]:
# change the columns name

# isko hum koi variables me store nahi karte toh vo change nahi hota, vo data frame me change nahi hua hai
df1 = df.rename(columns={'Salary': 'Monthly_Salary'})

In [65]:
df1

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000
2   Sweta   42           40000

if we want to change within that same dataframe

In [66]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True)
df

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000
2   Sweta   42           40000

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            3 non-null      str
 1   Age             3 non-null      int64
 2   Monthly_Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [68]:
df.describe() # yeh statical summary dikhata hai jo bhi numerical columns hai

             Age  Monthly_Salary
count   3.000000             3.0
mean   32.333333         30000.0
std    10.598742         10000.0
min    21.000000         20000.0
25%    27.500000         25000.0
50%    34.000000         30000.0
75%    38.000000         35000.0
max    42.000000         40000.0

In [69]:
df.describe(include="all")

          Name        Age  Monthly_Salary
count        3   3.000000             3.0
unique       3        NaN             NaN
top     Arpita        NaN             NaN
freq         1        NaN             NaN
mean       NaN  32.333333         30000.0
std        NaN  10.598742         10000.0
min        NaN  21.000000         20000.0
25%        NaN  27.500000         25000.0
50%        NaN  34.000000         30000.0
75%        NaN  38.000000         35000.0
max        NaN  42.000000         40000.0

### Save and Load data from csv

In [70]:
df.to_csv('Test_data.csv', index=False)  #export dataframe
#  if we dont want the index by default index is True

df.to_csv('Test_data.csv') #import dataframe

Import CSV

In [71]:
load_df = pd.read_csv('Test_data.csv')
print(load_df)

   Unnamed: 0    Name  Age  Monthly_Salary
0           0  Arpita   21           20000
1           1   Swati   34           30000
2           2   Sweta   42           40000

# Rows & COlumns - selection

In [72]:
# select columns
df[['Name']] # single columns
df[['Name', 'Age']]

     Name  Age
0  Arpita   21
1   Swati   34
2   Sweta   42

In [73]:
# select rows

# filter rows 
# loc - label based based index
df.loc[df.Name == 'Arpita']
df.loc[(df.Name == 'Swati') & (df.Monthly_Salary >= 30000)]

    Name  Age  Monthly_Salary
1  Swati   34           30000

### iloc - index-value based

In [74]:
df.iloc[0]
df.iloc[0:2] #start:stop:step

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000

#### Interview question

what is the difference between iloc and loc ?

both are indexing based and in iloc the last index is not included same as other programming language where as in loc it is included

In [75]:
df.loc[0:2]

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000
2   Sweta   42           40000

### Filter DataFrame

In [76]:
df['Age'] > 21
#  this will give true and false

0    False
1     True
2     True
Name: Age, dtype: bool

In [78]:
df[df['Age'] > 21]

    Name  Age  Monthly_Salary
1  Swati   34           30000
2  Sweta   42           40000

In [79]:
df1 = df[df['Age'] > 21]
df1

    Name  Age  Monthly_Salary
1  Swati   34           30000
2  Sweta   42           40000

In [80]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 10000)]

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000
2   Sweta   42           40000

In [83]:
df.where(df['Age'] > 21)

    Name   Age  Monthly_Salary
0    NaN   NaN             NaN
1  Swati  34.0         30000.0
2  Sweta  42.0         40000.0

In [84]:
df.where(df['Age'] > 21, other = "Not eligible")

           Name           Age Monthly_Salary
0  Not eligible  Not eligible   Not eligible
1         Swati            34          30000
2         Sweta            42          40000

### Rows and Columns - Operation (Add, Update, Delete)

In [85]:
df

     Name  Age  Monthly_Salary
0  Arpita   21           20000
1   Swati   34           30000
2   Sweta   42           40000

In [88]:
# add new column

df['Team'] = ['CEO', 'HR', 'CTO']
df

     Name  Age  Monthly_Salary Team
0  Arpita   21           20000  CEO
1   Swati   34           30000   HR
2   Sweta   42           40000  CTO

In [100]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

     Name  Age  Monthly_Salary     Team    Bonus
0  Arpita   21          100000      CEO  20000.0
1   Swati   34           30000       HR   6000.0
2   Sweta   42           40000      CTO   8000.0
3     ABC   21           29000  Manager   5800.0
4     ABC   21           29000  Manager   5800.0

In [103]:
# add new row

df.loc[len(df)] = ['ABC', 21,29000, 'Manager', 5600]
df

ValueError: cannot set a row with mismatched columns

In [92]:
len(df)

5

In [ ]:
# updatee value
df.loc[0, 'Monthly_Salary'] = 95000
df

     Name  Age  Monthly_Salary     Team   Bonus
0  Arpita   21           95000      CEO  4000.0
1   Swati   34           30000       HR  6000.0
2   Sweta   42           40000      CTO  8000.0
3     ABC   21           29000  Manager  5600.0
4     ABC   21           29000  Manager  5600.0

In [94]:
#update value - using column name

df.loc[df.Name == 'Arpita', 'Monthly_Salary'] = 100000
df

     Name  Age  Monthly_Salary     Team   Bonus
0  Arpita   21          100000      CEO  4000.0
1   Swati   34           30000       HR  6000.0
2   Sweta   42           40000      CTO  8000.0
3     ABC   21           29000  Manager  5600.0
4     ABC   21           29000  Manager  5600.0

In [ ]:
# delete value - row and column values

# by default it will delete rows  , axis = 0
df = df.drop(df[df.Name == 'ABC'].index)

     Name  Age  Monthly_Salary Team   Bonus
0  Arpita   21          100000  CEO  4000.0
1   Swati   34           30000   HR  6000.0
2   Sweta   42           40000  CTO  8000.0

In [ ]:
# drop column , axis=1
df.drop('Bonus', axis=1, inplace=True)  # drop column

In [102]:
df.drop(['Bonus', 'Team'], axis=1)  # delete multiple columns
df

KeyError: "['Bonus'] not found in axis"

In [106]:
# sort value
df.sort_values('Monthly_Salary') # Ascending order (by default)

df.sort_values('Monthly_Salary', ascending=False) # Descending order

     Name  Age  Monthly_Salary     Team
0  Arpita   21          100000      CEO
2   Sweta   42           40000      CTO
1   Swati   34           30000       HR
3     ABC   21           29000  Manager
4     ABC   21           29000  Manager

### Working With Date Values

In [ ]:
df1['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-26', '2024-03-3', '2024-06-6']

In [110]:
df['DOJ'].dtype
df

     Name  Age  Monthly_Salary     Team         DOJ
0  Arpita   21          100000      CEO  2024-01-01
1   Swati   34           30000       HR  2024-01-15
2   Sweta   42           40000      CTO  2024-03-26
3     ABC   21           29000  Manager   2024-03-3
4     ABC   21           29000  Manager   2024-06-6

In [111]:
df['DOJ'].dtype

In [112]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [113]:
df['DOJ'].dtype

dtype('<M8[us]')

<!-- how to verify check the date format  -->

### how to format the date and time

In [119]:
df1 = df

In [120]:
df1['DOJ2'] = ['01-02-2024', '23-04-2024', '02-04-2024', '05-05-2024', '6-02-2024']
df1

     Name  Age  Monthly_Salary     Team        DOJ        DOJ2
0  Arpita   21          100000      CEO 2024-01-01  01-02-2024
1   Swati   34           30000       HR 2024-01-15  23-04-2024
2   Sweta   42           40000      CTO 2024-03-26  02-04-2024
3     ABC   21           29000  Manager 2024-03-03  05-05-2024
4     ABC   21           29000  Manager 2024-06-06   6-02-2024

In [121]:
df1['DOJ2'].dtype

### Handling missing values

In [122]:
df

     Name  Age  Monthly_Salary     Team        DOJ        DOJ2
0  Arpita   21          100000      CEO 2024-01-01  01-02-2024
1   Swati   34           30000       HR 2024-01-15  23-04-2024
2   Sweta   42           40000      CTO 2024-03-26  02-04-2024
3     ABC   21           29000  Manager 2024-03-03  05-05-2024
4     ABC   21           29000  Manager 2024-06-06   6-02-2024

In [128]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ   DOJ2
0  False  False            True  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False           False  False  False  False
4  False  False           False  False  False  False

In [124]:
import numpy as np

In [127]:
df.loc[df.Name == 'Arpita', 'Monthly_Salary'] = np.nan
df

     Name  Age  Monthly_Salary     Team        DOJ        DOJ2
0  Arpita   21             NaN      CEO 2024-01-01  01-02-2024
1   Swati   34         30000.0       HR 2024-01-15  23-04-2024
2   Sweta   42         40000.0      CTO 2024-03-26  02-04-2024
3     ABC   21         29000.0  Manager 2024-03-03  05-05-2024
4     ABC   21         29000.0  Manager 2024-06-06   6-02-2024

In [129]:
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    1
Team              0
DOJ               0
DOJ2              0
dtype: int64

In [130]:
# how to remove null value
df.fillna(0)

     Name  Age  Monthly_Salary     Team        DOJ        DOJ2
0  Arpita   21             0.0      CEO 2024-01-01  01-02-2024
1   Swati   34         30000.0       HR 2024-01-15  23-04-2024
2   Sweta   42         40000.0      CTO 2024-03-26  02-04-2024
3     ABC   21         29000.0  Manager 2024-03-03  05-05-2024
4     ABC   21         29000.0  Manager 2024-06-06   6-02-2024

In [131]:
df

     Name  Age  Monthly_Salary     Team        DOJ        DOJ2
0  Arpita   21             NaN      CEO 2024-01-01  01-02-2024
1   Swati   34         30000.0       HR 2024-01-15  23-04-2024
2   Sweta   42         40000.0      CTO 2024-03-26  02-04-2024
3     ABC   21         29000.0  Manager 2024-03-03  05-05-2024
4     ABC   21         29000.0  Manager 2024-06-06   6-02-2024

### Aggregation and group by

In [132]:
df['Team'].value_counts()

Team
Manager    2
CEO        1
HR         1
CTO        1
Name: count, dtype: int64

In [133]:
df[df['Team'] == 'HR'].value_counts()

Name   Age  Monthly_Salary  Team  DOJ         DOJ2
Swati  34   30000.0         HR    2024-01-15  23-04-2024    1
Name: count, dtype: int64

In [ ]:
#  Groupby

df.groupby('Team')['Monthly_Salary'].sum() #aggregation based on group by

Team
CEO            0.0
CTO        40000.0
HR         30000.0
Manager    58000.0
Name: Monthly_Salary, dtype: float64

In [137]:

#  for avg we need to use mean

df.groupby('Team')['Monthly_Salary'].mean()

Team
CEO            NaN
CTO        40000.0
HR         30000.0
Manager    29000.0
Name: Monthly_Salary, dtype: float64

In [138]:
df.groupby('Team').agg({'Monthly_Salary': 'mean', 'Name': 'count'})

         Monthly_Salary  Name
Team
CEO                 NaN     1
CTO             40000.0     1
HR              30000.0     1
Manager         29000.0     2

### Concatenate and Merge Dataframe (JOINS)

In [139]:
df1 = pd.DataFrame({'ID': [1,2,3], 'Name': ['A', 'B', 'C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [140]:
df2 = pd.DataFrame({'ID': [1,2,3,4], 'Score': [88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79

In [ ]:
pd.concat([df1, df2], axis=0) #vertical / row level join - top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   3  NaN   77.0
3   4  NaN   79.0

In [143]:
pd.concat([df1, df2], axis=1) # horizontal / column level join - left to right

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

In [ ]:
# merge = join

pd.merge()