### Creating, Reading and Writing

In [2]:
import pandas as pd

#### Creating data

Dataframe - a dataframe is a table. It contains an array of individuals entries, each of which has a certain value Each entry corresponds to a row (or record) and a column

In [3]:
df = pd.DataFrame({'Yes': [50,21], 'No': [131,2]})
df

   Yes   No
0   50  131
1   21    2

In [4]:
pd.DataFrame({'Bob': ['I liked it', 'It was awful'],
              'Sue': ['Pretty good', 'Bland']})

            Bob          Sue
0    I liked it  Pretty good
1  It was awful        Bland

#### Series

In [5]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series([30,35,40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

#### read csv file

In [7]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv")
# find the shape of the DataFrame
wine_reviews.shape

(129971, 14)

### grab first five rows

In [8]:
wine_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#### to make pandas use that column for the index(instead of creating a new one from scratch), we can specify an index_col

In [9]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Indexing, Selecting & Assigning

In [12]:
reviews = pd.DataFrame({
    'country': ['Italy', 'France', 'Portugal'],
    'description': ['Excellent wine', 'Great taste', 'Delicious'],
    'points': [95, 87, 92],
    'price': [15.99, 12.99, 18.99],
    'province': ['Tuscany', 'Bordeaux', 'Douro'],
    'region_2': ['Chianti', 'Medoc', 'Douro']
})

reviews

    country     description  points  price  province region_2
0     Italy  Excellent wine      95  15.99   Tuscany  Chianti
1    France     Great taste      87  12.99  Bordeaux    Medoc
2  Portugal       Delicious      92  18.99     Douro    Douro

In [13]:
reviews.country

0       Italy
1      France
2    Portugal
Name: country, dtype: str

If we gave a python dictionary , we can access its values using the indexing ([]) operator. We can do the same with columns in a DataFrame.

In [14]:
reviews['country']

0       Italy
1      France
2    Portugal
Name: country, dtype: str

In [15]:
reviews['country'][0]

'Italy'

iloc - index based selection

In [16]:
reviews.iloc[0]

country                 Italy
description    Excellent wine
points                     95
price                   15.99
province              Tuscany
region_2              Chianti
Name: 0, dtype: object

In [17]:
reviews.iloc[:, 0]

0       Italy
1      France
2    Portugal
Name: country, dtype: str

In [18]:
reviews.iloc[1:3, 0]

1      France
2    Portugal
Name: country, dtype: str

### it is possible to pass a list

In [19]:
reviews.iloc[[0,1,2], 0]

0       Italy
1      France
2    Portugal
Name: country, dtype: str

 negative numbers - start counting forwards from the end of the values

In [20]:
reviews.iloc[-5:]

    country     description  points  price  province region_2
0     Italy  Excellent wine      95  15.99   Tuscany  Chianti
1    France     Great taste      87  12.99  Bordeaux    Medoc
2  Portugal       Delicious      92  18.99     Douro    Douro

label-based selection

In [23]:
reviews.loc[0, 'country']

'Italy'

In [22]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

KeyError: "['taster_name', 'taster_twitter_handle'] not in index"